export default [
    {
        id: 1,
        name: 'Huawei Mate 40 RS保时捷设计款（5G款） 白色',
        brand: 'mate 系列',
        image: 'Huawei Products/Huawei Mate 40 RS/Huawei Mate 40 RS white.jpg',
        sales: 10000,
        cost: 10999,
        color: '白色',
        length: 10,
        introductionPath: '../Huawei Products/Huawei Mate 40 RS/'
    },
    {
        id: 2,
        name: 'Huawei Mate 40 RS保时捷设计款（5G款） 黑色',
        brand: 'mate 系列',
        image: 'Huawei Products/Huawei Mate 40 RS/Huawei Mate 40 RS black.jpg',
        sales: 9900,
        cost: 10999,
        color: '黑色',
        length: 10,
        introductionPath: '../Huawei Products/Huawei Mate 40 RS/'
    },
    {
        id: 3,
        name: 'Huawei Mate 40 Pro+（5G款） 白色',
        brand: 'mate 系列',
        image: 'Huawei Products/Huawei Mate 40 Pro+/Huawei Mate 40 Pro+ white.jpg',
        sales: 15900,
        cost: 8999,
        color: '白色',
        length: 20,
        introductionPath: '../Huawei Products/Huawei Mate 40 Pro+/'
    },
    {
        id: 4,
        name: 'Huawei Mate 40 Pro+（5G款） 黑色',
        brand: 'mate 系列',
        image: 'Huawei Products/Huawei Mate 40 Pro+/Huawei Mate 40 Pro+ black.jpg',
        sales: 23900,
        cost: 8999,
        color: '黑色',
        length: 20,
        introductionPath: '../Huawei Products/Huawei Mate 40 Pro+/'
    },
    {
        id: 5,
        name: 'Huawei Mate 40 Pro（5G款） 白色',
        brand: 'mate 系列',
        image: 'Huawei Products/Huawei Mate 40 Pro/Huawei Mate 40 Pro white.jpg',
        sales: 45900,
        cost: 6299,
        color: '白色',
        length: 14,
        introductionPath: '../Huawei Products/Huawei Mate 40 Pro/'
    },
    {
        id: 6,
        name: 'Huawei Mate 40 Pro（5G款） 黑色',
        brand: 'mate 系列',
        image: 'Huawei Products/Huawei Mate 40 Pro/Huawei Mate 40 Pro black.jpg',
        sales: 42900,
        cost: 6299,
        color: '黑色',
        length: 14,
        introductionPath: '../Huawei Products/Huawei Mate 40 Pro/'
    },
    {
        id: 7,
        name: 'Huawei Mate 40 Pro（5G款） 夏日胡杨',
        brand: 'mate 系列',
        image: 'Huawei Products/Huawei Mate 40 Pro/Huawei Mate 40 Pro summer.jpg',
        sales: 39900,
        cost: 6299,
        color: '夏日胡杨',
        length: 14,
        introductionPath: '../Huawei Products/Huawei Mate 40 Pro/'
    },
    {
        id: 8,
        name: 'Huawei Mate 40 Pro（5G款） 秋日胡杨',
        brand: 'mate 系列',
        image: 'Huawei Products/Huawei Mate 40 Pro/Huawei Mate 40 Pro automn.jpg',
        sales: 27900,
        cost: 6299,
        color: '秋日胡杨',
        length: 14,
        introductionPath: '../Huawei Products/Huawei Mate 40 Pro/'
    },
    {
        id: 9,
        name: 'Huawei Mate 40 Pro（5G款） 秘银色',
        brand: 'mate 系列',
        image: 'Huawei Products/Huawei Mate 40 Pro/Huawei Mate 40 Pro yin.jpg',
        sales: 23900,
        cost: 6299,
        color: '秘银色',
        length: 14,
        introductionPath: '../Huawei Products/Huawei Mate 40 Pro/'
    },
    {
        id: 10,
        name: 'Huawei P 40 Pro+（5G款） 白色',
        brand: 'P 系列',
        image: 'Huawei Products/Huawei P 40 Pro+/Huawei P 40 Pro+ white.jpg',
        sales: 108900,
        cost: 7999,
        color: '白色',
        length: 21,
        introductionPath: '../Huawei Products/Huawei P 40 Pro+/'
    },
    {
        id: 11,
        name: 'Huawei P 40 Pro+（5G款） 黑色',
        brand: 'P 系列',
        image: 'Huawei Products/Huawei P 40 Pro+/Huawei P 40 Pro+ black.jpg',
        sales: 98900,
        cost: 7999,
        color: '黑色',
        length: 21,
        introductionPath: '../Huawei Products/Huawei P 40 Pro+/'
    },
    {
        id: 12,
        name: 'Huawei nova 8 Pro 黑色',
        brand: 'nova 系列',
        image: 'Huawei Products/Huawei nova 8 Pro/Huawei nova 8 Pro black.jpg',
        sales: 76580,
        cost: 3799,
        color: '黑色',
        length: 12,
        introductionPath: '../Huawei Products/Huawei nova 8 Pro/'
    },
    {
        id: 13,
        name: 'Huawei nova 8 Pro 8号色',
        brand: 'nova 系列',
        image: 'Huawei Products/Huawei nova 8 Pro/Huawei nova 8 Pro 8th.jpg',
        sales: 96580,
        cost: 3799,
        color: '8号色',
        length: 12,
        introductionPath: '../Huawei Products/Huawei nova 8 Pro/'
    },
    {
        id: 14,
        name: 'Huawei nova 8 Pro 绿境森林',
        brand: 'nova 系列',
        image: 'Huawei Products/Huawei nova 8 Pro/Huawei nova 8 Pro green.jpg',
        sales: 54580,
        cost: 3799,
        color: '绿境森林',
        length: 12,
        introductionPath: '../Huawei Products/Huawei nova 8 Pro/'
    },
    {
        id: 15,
        name: 'Huawei Mate Xs 5G全网通',
        brand: 'mate X 系列',
        image: 'Huawei Products/Huawei Mate Xs 5G/Huawei Mate Xs 5G.jpg',
        sales: 2000,
        cost: 16999,
        color: '黑色',
        length: 10,
        introductionPath: '../Huawei Products/Huawei Mate Xs 5G/'
    },
    {
        id: 16,
        name: 'Huawei Mate Book X Pro 2021款 夏日胡杨',
        brand: 'mate Book 系列',
        image: 'Huawei Products/Huawei Mate Book X Pro/Huawei Mate Book X Pro green.jpg',
        sales: 12300,
        cost: 10999,
        color: '夏日胡杨',
        length: 8,
        introductionPath: '../Huawei Products/Huawei Mate Book X Pro/'
    },
    {
        id: 17,
        name: 'Huawei Mate Book X Pro 2021款 深空灰',
        brand: 'mate Book 系列',
        image: 'Huawei Products/Huawei Mate Book X Pro/Huawei Mate Book X Pro hui.jpg',
        sales: 22300,
        cost: 10999,
        color: '深空灰',
        length: 8,
        introductionPath: '../Huawei Products/Huawei Mate Book X Pro/'
    },
    {
        id: 18,
        name: 'Huawei Mate Book X Pro 2021款 秘银色',
        brand: 'mate Book 系列',
        image: 'Huawei Products/Huawei Mate Book X Pro/Huawei Mate Book X Pro yin.jpg',
        sales: 13300,
        cost: 10999,
        color: '秘银色',
        length: 8,
        introductionPath: '../Huawei Products/Huawei Mate Book X Pro/'
    },
    {
        id: 19,
        name: 'Huawei Mate Book X Pro 2021款 玫瑰金',
        brand: 'mate Book 系列',
        image: 'Huawei Products/Huawei Mate Book X Pro/Huawei Mate Book X Pro jin.jpg',
        sales: 42300,
        cost: 10999,
        color: '玫瑰金',
        length: 8,
        introductionPath: '../Huawei Products/Huawei Mate Book X Pro/'
    },
    {
        id: 20,
        name: 'Huawei Mate Book X 2021款 夏日胡杨',
        brand: 'mate Book 系列',
        image: 'Huawei Products/Huawei Mate Book X/Huawei Mate Book X green.jpg',
        sales: 26300,
        cost: 9999,
        color: '夏日胡杨',
        length: 4,
        introductionPath: '../Huawei Products/Huawei Mate Book X/'
    },
    {
        id: 21,
        name: 'Huawei Mate Book X 2021款 深空灰',
        brand: 'mate Book 系列',
        image: 'Huawei Products/Huawei Mate Book X/Huawei Mate Book X hui.jpg',
        sales: 26300,
        cost: 9999,
        color: '深空灰',
        length: 4,
        introductionPath: '../Huawei Products/Huawei Mate Book X/'
    },
    {
        id: 22,
        name: 'Huawei Mate Book X 2021款 秘银色',
        brand: 'mate Book 系列',
        image: 'Huawei Products/Huawei Mate Book X/Huawei Mate Book X yin.jpg',
        sales: 13300,
        cost: 9999,
        color: '秘银色',
        length: 4,
        introductionPath: '../Huawei Products/Huawei Mate Book X/'
    },
    {
        id: 23,
        name: 'Huawei Mate Book 14 2021款 深空灰',
        brand: 'mate Book 系列',
        image: 'Huawei Products/Huawei Mate Book 14/Huawei Mate Book 14 hui.jpg',
        sales: 75300,
        cost: 6999,
        color: '深空灰',
        length: 6,
        introductionPath: '../Huawei Products/Huawei Mate Book 14/'
    },
    {
        id: 24,
        name: 'Huawei Mate Book 14 2021款 秘银色',
        brand: 'mate Book 系列',
        image: 'Huawei Products/Huawei Mate Book 14/Huawei Mate Book 14 yin.jpg',
        sales: 45300,
        cost: 6999,
        color: '秘银色',
        length: 6,
        introductionPath: '../Huawei Products/Huawei Mate Book 14/'
    },
    {
        id: 25,
        name: 'Huawei MatePad 10.9英寸 2021款 深空灰',
        brand: 'Pad 系列',
        image: 'Huawei Products/Huawei Mate Pad/Huawei Mate Pad hui.jpg',
        sales: 13500,
        cost: 3599,
        color: '深空灰',
        length: 6,
        introductionPath: '../Huawei Products/Huawei Mate Pad/'
    },
    {
        id: 26,
        name: 'Huawei MatePad 10.9英寸 2021款 白色',
        brand: 'Pad 系列',
        image: 'Huawei Products/Huawei Mate Pad/Huawei Mate Pad white.jpg',
        sales: 17500,
        cost: 3599,
        color: '白色',
        length: 6,
        introductionPath: '../Huawei Products/Huawei Mate Pad/'
    },
    {
        id: 27,
        name: 'Huawei MatePad 12.6英寸 2021款 深空灰',
        brand: 'Pad 系列',
        image: 'Huawei Products/Huawei Mate Pad/Huawei Mate Pad 12 hui.jpg',
        sales: 7500,
        cost: 5299,
        color: '深空灰',
        length: 6,
        introductionPath: '../Huawei Products/Huawei Mate Pad/'
    },
    {
        id: 28,
        name: 'Huawei MatePad 12.6英寸 2021款 白色',
        brand: 'Pad 系列',
        image: 'Huawei Products/Huawei Mate Pad/Huawei Mate Pad 12 white.jpg',
        sales: 4500,
        cost: 5299,
        color: '白色',
        length: 6,
        introductionPath: '../Huawei Products/Huawei Mate Pad/'
    },
    {
        id: 29,
        name: 'Huawei MatePad 12.6英寸 2021款 夏日胡杨',
        brand: 'Pad 系列',
        image: 'Huawei Products/Huawei Mate Pad/Huawei Mate Pad 12 summer.jpg',
        sales: 8500,
        cost: 5299,
        color: '夏日胡杨',
        length: 6,
        introductionPath: '../Huawei Products/Huawei Mate Pad/'
    },
    {
        id: 30,
        name: 'Huawei freebuds Pro 秘银色',
        brand: 'Freebuds 系列',
        image: 'Huawei Products/Huawei freebuds Pro/Huawei freebuds Pro.jpg',
        sales: 29500,
        cost: 1199,
        color: '秘银色',
        length: 10,
        introductionPath: '../Huawei Products/Huawei freebuds Pro/'
    },
    {
        id: 31,
        name: 'Huawei freebuds Pro 黑色',
        brand: 'Freebuds 系列',
        image: 'Huawei Products/Huawei freebuds Pro/Huawei freebuds Pro black.jpg',
        sales: 19500,
        cost: 1199,
        color: '黑色',
        length: 10,
        introductionPath: '../Huawei Products/Huawei freebuds Pro/'
    },
    {
        id: 32,
        name: 'Huawei freebuds Pro 白色',
        brand: 'Freebuds 系列',
        image: 'Huawei Products/Huawei freebuds Pro/Huawei freebuds Pro white.jpg',
        sales: 11500,
        cost: 1199,
        color: '白色',
        length: 10,
        introductionPath: '../Huawei Products/Huawei freebuds Pro/'
    },
    {
        id: 33,
        name: 'Huawei freebuds 4 秘银色',
        brand: 'Freebuds 系列',
        image: 'Huawei Products/Huawei freebuds 4/Huawei freebuds 4 yin.jpg',
        sales: 19900,
        cost: 999,
        color: '秘银色',
        length: 10,
        introductionPath: '../Huawei Products/Huawei freebuds 4/'
    },
    {
        id: 34,
        name: 'Huawei freebuds Pro 白色',
        brand: 'Freebuds 系列',
        image: 'Huawei Products/Huawei freebuds 4/Huawei freebuds 4 white.jpg',
        sales: 7500,
        cost: 999,
        color: '白色',
        length: 10,
        introductionPath: '../Huawei Products/Huawei freebuds 4/'
    },
    {
        id: 35,
        name: 'Huawei freebuds studio 玫瑰金',
        brand: 'Freebuds 系列',
        image: 'Huawei Products/Huawei freebuds studio/Huawei freebuds studio.jpg',
        sales: 36500,
        cost: 1899,
        color: '玫瑰金',
        length: 7,
        introductionPath: '../Huawei Products/Huawei freebuds studio/'
    },
    {
        id: 36,
        name: 'Huawei freebuds studio 黑色',
        brand: 'Freebuds 系列',
        image: 'Huawei Products/Huawei freebuds studio/Huawei freebuds studio black.jpg',
        sales: 13500,
        cost: 1899,
        color: '黑色',
        length: 7,
        introductionPath: '../Huawei Products/Huawei freebuds studio/'
    }
]